# Dockerfile
# RUN apk add --no-cache gcc libffi-dev musl-dev postgresql-dev
FROM python:3.10-alpine

RUN apk add g++
RUN apk add linux-headers

WORKDIR /app
COPY ./docker/poetry-modules.txt /app/api/

RUN apk update; apk upgrade; ln -s /usr/bin/python /usr/bin/python3.10; addgroup -S apigroup && adduser -S api -G apigroup
USER api
WORKDIR /app/api

RUN pip install -r poetry-modules.txt; wget -q -O - "$@" https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

ENV PATH=$PATH:/home/api/.local/bin:/home/api/.poetry/bin

COPY ./poetry.lock ./pyproject.toml ./
RUN poetry install --no-dev

COPY ./main.py ./app ./
EXPOSE 8000
ENTRYPOINT poetry run python main.py
